version: '3.3'
services:
  collect.mongo:  
    container_name: collect.mongo
    image: mongo:4.2
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    networks: 
      dehia:
      backend:
        aliases:
          - collect.mongo
    command: mongod --auth --bind_ip 0.0.0.0
    volumes:
      - ./docker/mongo/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  collect.app:
    container_name: collect.app
    image: mokocchi/dehia-collect
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on: 
      - ${DATABASE_HOST}
    environment: 
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      DATABASE_HOST: ${DATABASE_HOST}
      SITE_BASE_URL: ${SITE_BASE_URL}
      DEFINE_BASE_URL: ${DEFINE_BASE_URL}
      AUTH_BASE_URL: $AUTH_BASE_URL
      WAIT_HOSTS: collect.mongo:27017
      WAIT_SLEEP_INTERVAL: 10
      WAIT_BEFORE_HOSTS: 10
      WAIT_TIMEOUT: 350
    restart: on-failure
    networks: 
      backend:
      dehia:
        aliases:
          - collect.app

networks:
  dehia:
    external: true
  backend:
    external: false